# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/data_warehouse/management/v2/migrations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cavnue.third_party.bq.v1 import bq_field_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__field__pb2
from cavnue.third_party.bq.v1 import bq_table_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__table__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=cavnue/messages/data_warehouse/management/v2/migrations.proto\x12,cavnue.messages.data_warehouse.management.v2\x1a\'cavnue/third_party/bq/v1/bq_field.proto\x1a\'cavnue/third_party/bq/v1/bq_table.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x04\n\tMigration\x12\x46\n\x08start_ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x13\x8a\xf9+\x0f\x08\x01\x12\tTIMESTAMP8\x01H\x00\x88\x01\x01\x12\x42\n\x06\x65nd_ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x11\x8a\xf9+\r\x08\x01\x12\tTIMESTAMPH\x01\x88\x01\x01\x12 \n\tcohort_id\x18\x03 \x01(\x03\x42\x08\x8a\xf9+\x04\x08\x01@\x01H\x02\x88\x01\x01\x12]\n\x07trigger\x18\x04 \x01(\x0e\x32?.cavnue.messages.data_warehouse.management.v2.Migration.TriggerB\x06\x8a\xf9+\x02\x08\x01H\x03\x88\x01\x01\x12\x10\n\x08\x64\x61ta_ids\x18\x05 \x03(\x03\x12\x1a\n\nidentifier\x18\x06 \x01(\tB\x06\x8a\xf9+\x02\x08\x01\x12\x15\n\rsimulation_id\x18\x07 \x01(\t\"h\n\x07Trigger\x12\x17\n\x13TRIGGER_UNSPECIFIED\x10\x00\x12\x11\n\rTRIGGER_EVENT\x10\x01\x12\x12\n\x0eTRIGGER_MANUAL\x10\x02\x12\x1d\n\x19TRIGGER_DISTRIBUTION_TIME\x10\x03:\x10\x82\xf9+\x0c\n\nMigrationsB\x0b\n\t_start_tsB\t\n\x07_end_tsB\x0c\n\n_cohort_idB\n\n\x08_triggerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.data_warehouse.management.v2.migrations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MIGRATION.fields_by_name['start_ts']._options = None
  _MIGRATION.fields_by_name['start_ts']._serialized_options = b'\212\371+\017\010\001\022\tTIMESTAMP8\001'
  _MIGRATION.fields_by_name['end_ts']._options = None
  _MIGRATION.fields_by_name['end_ts']._serialized_options = b'\212\371+\r\010\001\022\tTIMESTAMP'
  _MIGRATION.fields_by_name['cohort_id']._options = None
  _MIGRATION.fields_by_name['cohort_id']._serialized_options = b'\212\371+\004\010\001@\001'
  _MIGRATION.fields_by_name['trigger']._options = None
  _MIGRATION.fields_by_name['trigger']._serialized_options = b'\212\371+\002\010\001'
  _MIGRATION.fields_by_name['identifier']._options = None
  _MIGRATION.fields_by_name['identifier']._serialized_options = b'\212\371+\002\010\001'
  _MIGRATION._options = None
  _MIGRATION._serialized_options = b'\202\371+\014\n\nMigrations'
  _globals['_MIGRATION']._serialized_start=227
  _globals['_MIGRATION']._serialized_end=750
  _globals['_MIGRATION_TRIGGER']._serialized_start=578
  _globals['_MIGRATION_TRIGGER']._serialized_end=682
# @@protoc_insertion_point(module_scope)
