# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/data_warehouse/management/v2/camera_media_outputs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cavnue.third_party.bq.v1 import bq_field_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__field__pb2
from cavnue.third_party.bq.v1 import bq_table_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__table__pb2
from cavnue.messages.common.v1 import field_options_pb2 as cavnue_dot_messages_dot_common_dot_v1_dot_field__options__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGcavnue/messages/data_warehouse/management/v2/camera_media_outputs.proto\x12,cavnue.messages.data_warehouse.management.v2\x1a\'cavnue/third_party/bq/v1/bq_field.proto\x1a\'cavnue/third_party/bq/v1/bq_table.proto\x1a-cavnue/messages/common/v1/field_options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n\x11\x43\x61meraMediaOutput\x12\x1c\n\x03uri\x18\x01 \x01(\tB\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x00\x88\x01\x01\x12 \n\x07\x64\x61ta_id\x18\x02 \x01(\x03\x42\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x01\x88\x01\x01\x12@\n\x02ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x13\x8a\xf9+\x0f\x08\x01\x12\tTIMESTAMP8\x01H\x02\x88\x01\x01:\x18\x82\xf9+\x14\n\x12\x43\x61meraMediaOutputsB\x06\n\x04_uriB\n\n\x08_data_idB\x05\n\x03_ts\"\xec\x02\n\x19\x43\x61meraMediaOutputMetadata\x12\x1c\n\x03uri\x18\x01 \x01(\tB\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x00\x88\x01\x01\x12\x44\n\x08start_ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x11\x8a\xf9+\r\x08\x01\x12\tTIMESTAMPH\x01\x88\x01\x01\x12\x1f\n\x06height\x18\x03 \x01(\rB\n\x88\xf1\x04\x04\x8a\xf9+\x02\x08\x01H\x02\x88\x01\x01\x12\x1e\n\x05width\x18\x04 \x01(\rB\n\x88\xf1\x04\x04\x8a\xf9+\x02\x08\x01H\x03\x88\x01\x01\x12!\n\x08\x64uration\x18\x05 \x01(\x02\x42\n\x88\xf1\x04\x08\x8a\xf9+\x02\x08\x01H\x04\x88\x01\x01\x12\x1f\n\nframe_rate\x18\x06 \x01(\rB\x06\x8a\xf9+\x02\x08\x01H\x05\x88\x01\x01: \x82\xf9+\x1c\n\x1a\x43\x61meraMediaOutputsMetadataB\x06\n\x04_uriB\x0b\n\t_start_tsB\t\n\x07_heightB\x08\n\x06_widthB\x0b\n\t_durationB\r\n\x0b_frame_rateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.data_warehouse.management.v2.camera_media_outputs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAMEDIAOUTPUT.fields_by_name['uri']._options = None
  _CAMERAMEDIAOUTPUT.fields_by_name['uri']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUT.fields_by_name['data_id']._options = None
  _CAMERAMEDIAOUTPUT.fields_by_name['data_id']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUT.fields_by_name['ts']._options = None
  _CAMERAMEDIAOUTPUT.fields_by_name['ts']._serialized_options = b'\212\371+\017\010\001\022\tTIMESTAMP8\001'
  _CAMERAMEDIAOUTPUT._options = None
  _CAMERAMEDIAOUTPUT._serialized_options = b'\202\371+\024\n\022CameraMediaOutputs'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['uri']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['uri']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['start_ts']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['start_ts']._serialized_options = b'\212\371+\r\010\001\022\tTIMESTAMP'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['height']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['height']._serialized_options = b'\210\361\004\004\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['width']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['width']._serialized_options = b'\210\361\004\004\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['duration']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['duration']._serialized_options = b'\210\361\004\010\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['frame_rate']._options = None
  _CAMERAMEDIAOUTPUTMETADATA.fields_by_name['frame_rate']._serialized_options = b'\212\371+\002\010\001'
  _CAMERAMEDIAOUTPUTMETADATA._options = None
  _CAMERAMEDIAOUTPUTMETADATA._serialized_options = b'\202\371+\034\n\032CameraMediaOutputsMetadata'
  _globals['_CAMERAMEDIAOUTPUT']._serialized_start=284
  _globals['_CAMERAMEDIAOUTPUT']._serialized_end=486
  _globals['_CAMERAMEDIAOUTPUTMETADATA']._serialized_start=489
  _globals['_CAMERAMEDIAOUTPUTMETADATA']._serialized_end=853
# @@protoc_insertion_point(module_scope)
