// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cavnue/messages/common/v1/field_options.proto

#include "cavnue/messages/common/v1/field_options.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace cavnue {
namespace messages {
namespace common {
namespace v1 {
}  // namespace v1
}  // namespace common
}  // namespace messages
}  // namespace cavnue
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto = nullptr;
const ::uint32_t TableStruct_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n-cavnue/messages/common/v1/field_option"
    "s.proto\022\031cavnue.messages.common.v1\032 goog"
    "le/protobuf/descriptor.proto*\240\003\n\005Units\022\025"
    "\n\021UNITS_UNSPECIFIED\020\000\022\033\n\027UNITS_METERS_PE"
    "R_SECOND\020\001\022#\n\037UNITS_METERS_PER_SECOND_SQ"
    "UARED\020\002\022\035\n\031UNITS_KILOMETERS_PER_HOUR\020\003\022\020"
    "\n\014UNITS_PIXELS\020\004\022\020\n\014UNITS_METERS\020\005\022\021\n\rUN"
    "ITS_SECONDS\020\007\022\026\n\022UNITS_MILLISECONDS\020\010\022\021\n"
    "\rUNITS_RADIANS\020\t\022\021\n\rUNITS_DEGREES\020\n\022\022\n\016U"
    "NITS_DECIBELS\020\013\022\036\n\032UNITS_MILLIMETERS_PER"
    "_HOUR\020\014\022\021\n\rUNITS_CELSIUS\020\r\022\034\n\030UNITS_DEGR"
    "EES_PER_SECOND\020\016\022\'\n#UNITS_VEHICLES_PER_M"
    "ETER_PER_SECOND\020\017\022\034\n\030UNITS_VEHICLES_PER_"
    "METER\020\020*]\n\003CRS\022\023\n\017CRS_UNSPECIFIED\020\000\022\r\n\tC"
    "RS_WGS84\020\001\022\013\n\007CRS_UTM\020\002\022\013\n\007CRS_ENU\020\003\022\013\n\007"
    "CRS_NED\020\004\022\013\n\007CRS_EGO\020\005:V\n\005units\022\035.google"
    ".protobuf.FieldOptions\030\221N \001(\0162 .cavnue.m"
    "essages.common.v1.UnitsR\005units:P\n\003crs\022\035."
    "google.protobuf.FieldOptions\030\222N \001(\0162\036.ca"
    "vnue.messages.common.v1.CRSR\003crs:3\n\004rows"
    "\022\035.google.protobuf.FieldOptions\030\241\234\001 \001(\rR"
    "\004rows:3\n\004cols\022\035.google.protobuf.FieldOpt"
    "ions\030\242\234\001 \001(\rR\004cols:E\n\rautogenerated\022\035.go"
    "ogle.protobuf.FieldOptions\030\321\206\003 \001(\010R\rauto"
    "generated:\?\n\nderivation\022\035.google.protobu"
    "f.FieldOptions\030\322\206\003 \003(\tR\nderivation:@\n\013pr"
    "imary_key\022\035.google.protobuf.FieldOptions"
    "\030\323\206\003 \001(\010R\nprimaryKeyb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto = {
    false,
    false,
    1108,
    descriptor_table_protodef_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto,
    "cavnue/messages/common/v1/field_options.proto",
    &descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto_once,
    descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto,
    file_level_service_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto_getter() {
  return &descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto(&descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto);
namespace cavnue {
namespace messages {
namespace common {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Units_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto);
  return file_level_enum_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto[0];
}
bool Units_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
      return true;
    default:
      return false;
  }
}
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CRS_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto);
  return file_level_enum_descriptors_cavnue_2fmessages_2fcommon_2fv1_2ffield_5foptions_2eproto[1];
}
bool CRS_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::cavnue::messages::common::v1::Units, ::cavnue::messages::common::v1::Units_IsValid>, 14, false>
  units(kUnitsFieldNumber, static_cast< ::cavnue::messages::common::v1::Units >(0), nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::cavnue::messages::common::v1::CRS, ::cavnue::messages::common::v1::CRS_IsValid>, 14, false>
  crs(kCrsFieldNumber, static_cast< ::cavnue::messages::common::v1::CRS >(0), nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>
  rows(kRowsFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< ::uint32_t >, 13, false>
  cols(kColsFieldNumber, 0u, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  autogenerated(kAutogeneratedFieldNumber, false, nullptr);
const std::string derivation_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedStringTypeTraits, 9, false>
  derivation(kDerivationFieldNumber, derivation_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false>
  primary_key(kPrimaryKeyFieldNumber, false, nullptr);
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace messages
}  // namespace cavnue
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
