# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/geometry/v1/pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cavnue.messages.geometry.v1 import point_pb2 as cavnue_dot_messages_dot_geometry_dot_v1_dot_point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&cavnue/messages/geometry/v1/pose.proto\x12\x1b\x63\x61vnue.messages.geometry.v1\x1a\'cavnue/messages/geometry/v1/point.proto\"4\n\x08\x41ttitude\x12\x0c\n\x04roll\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\"\x80\x02\n\x04Pose\x12\x33\n\x05point\x18\x01 \x01(\x0b\x32$.cavnue.messages.geometry.v1.Point3f\x12\x39\n\x08\x61ttitude\x18\x02 \x01(\x0b\x32%.cavnue.messages.geometry.v1.AttitudeH\x00\x12\x39\n\x05\x61ngle\x18\x03 \x01(\x0b\x32(.cavnue.messages.geometry.v1.QuaternionfH\x00\x12\x36\n\x04none\x18\x04 \x01(\x0b\x32&.cavnue.messages.geometry.v1.Pose.NoneH\x00\x1a\x06\n\x04NoneB\r\n\x0borientationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.geometry.v1.pose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ATTITUDE']._serialized_start=112
  _globals['_ATTITUDE']._serialized_end=164
  _globals['_POSE']._serialized_start=167
  _globals['_POSE']._serialized_end=423
  _globals['_POSE_NONE']._serialized_start=402
  _globals['_POSE_NONE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
