# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/data_warehouse/management/v1/labeling.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cavnue.third_party.bq.v1 import bq_field_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__field__pb2
from cavnue.third_party.bq.v1 import bq_table_pb2 as cavnue_dot_third__party_dot_bq_dot_v1_dot_bq__table__pb2
from cavnue.messages.common.v1 import field_options_pb2 as cavnue_dot_messages_dot_common_dot_v1_dot_field__options__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;cavnue/messages/data_warehouse/management/v1/labeling.proto\x12,cavnue.messages.data_warehouse.management.v1\x1a\'cavnue/third_party/bq/v1/bq_field.proto\x1a\'cavnue/third_party/bq/v1/bq_table.proto\x1a-cavnue/messages/common/v1/field_options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n\x05Scale\x12\x33\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x42\x1c\x88\xb5\x18\x01\x92\xb5\x18\nidentifier\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x00\x88\x01\x01\x12 \n\x07\x64\x61ta_id\x18\x02 \x01(\x03\x42\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x01\x88\x01\x01\x12\x1f\n\nidentifier\x18\x03 \x01(\tB\x06\x8a\xf9+\x02\x08\x01H\x02\x88\x01\x01\x12\x1c\n\x07project\x18\x04 \x01(\tB\x06\x8a\xf9+\x02\x08\x01H\x03\x88\x01\x01:\x0b\x82\xf9+\x07\n\x05ScaleB\x0b\n\t_batch_idB\n\n\x08_data_idB\r\n\x0b_identifierB\n\n\x08_project\"\xf9\x01\n\x08ScaleLog\x12#\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x42\x0c\x98\xb5\x18\x01\x8a\xf9+\x04\x08\x01@\x01H\x00\x88\x01\x01\x12 \n\x07\x64\x61ta_id\x18\x02 \x01(\x03\x42\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x01\x88\x01\x01\x12\x44\n\x08\x61udit_ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x11\x8a\xf9+\r\x08\x01\x12\tTIMESTAMPH\x02\x88\x01\x01\x12\x1f\n\x06status\x18\x04 \x01(\tB\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x03\x88\x01\x01:\x0e\x82\xf9+\n\n\x08ScaleLogB\x0b\n\t_batch_idB\n\n\x08_data_idB\x0b\n\t_audit_tsB\t\n\x07_status\"\xdf\x01\n\rSimulationRun\x12#\n\x08\x62\x61tch_id\x18\x01 \x01(\x03\x42\x0c\x98\xb5\x18\x01\x8a\xf9+\x04\x08\x01@\x01H\x00\x88\x01\x01\x12&\n\rsimulation_id\x18\x02 \x01(\tB\n\x98\xb5\x18\x01\x8a\xf9+\x02\x08\x01H\x01\x88\x01\x01\x12\x1f\n\nidentifier\x18\x03 \x01(\tB\x06\x8a\xf9+\x02\x08\x01H\x02\x88\x01\x01\x12\x1c\n\x08metadata\x18\x04 \x01(\tB\n\x8a\xf9+\x06\x12\x04JSON:\x14\x82\xf9+\x10\n\x0eSimulationRunsB\x0b\n\t_batch_idB\x10\n\x0e_simulation_idB\r\n\x0b_identifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.data_warehouse.management.v1.labeling_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCALE.fields_by_name['batch_id']._options = None
  _SCALE.fields_by_name['batch_id']._serialized_options = b'\210\265\030\001\222\265\030\nidentifier\230\265\030\001\212\371+\002\010\001'
  _SCALE.fields_by_name['data_id']._options = None
  _SCALE.fields_by_name['data_id']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _SCALE.fields_by_name['identifier']._options = None
  _SCALE.fields_by_name['identifier']._serialized_options = b'\212\371+\002\010\001'
  _SCALE.fields_by_name['project']._options = None
  _SCALE.fields_by_name['project']._serialized_options = b'\212\371+\002\010\001'
  _SCALE._options = None
  _SCALE._serialized_options = b'\202\371+\007\n\005Scale'
  _SCALELOG.fields_by_name['batch_id']._options = None
  _SCALELOG.fields_by_name['batch_id']._serialized_options = b'\230\265\030\001\212\371+\004\010\001@\001'
  _SCALELOG.fields_by_name['data_id']._options = None
  _SCALELOG.fields_by_name['data_id']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _SCALELOG.fields_by_name['audit_ts']._options = None
  _SCALELOG.fields_by_name['audit_ts']._serialized_options = b'\212\371+\r\010\001\022\tTIMESTAMP'
  _SCALELOG.fields_by_name['status']._options = None
  _SCALELOG.fields_by_name['status']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _SCALELOG._options = None
  _SCALELOG._serialized_options = b'\202\371+\n\n\010ScaleLog'
  _SIMULATIONRUN.fields_by_name['batch_id']._options = None
  _SIMULATIONRUN.fields_by_name['batch_id']._serialized_options = b'\230\265\030\001\212\371+\004\010\001@\001'
  _SIMULATIONRUN.fields_by_name['simulation_id']._options = None
  _SIMULATIONRUN.fields_by_name['simulation_id']._serialized_options = b'\230\265\030\001\212\371+\002\010\001'
  _SIMULATIONRUN.fields_by_name['identifier']._options = None
  _SIMULATIONRUN.fields_by_name['identifier']._serialized_options = b'\212\371+\002\010\001'
  _SIMULATIONRUN.fields_by_name['metadata']._options = None
  _SIMULATIONRUN.fields_by_name['metadata']._serialized_options = b'\212\371+\006\022\004JSON'
  _SIMULATIONRUN._options = None
  _SIMULATIONRUN._serialized_options = b'\202\371+\020\n\016SimulationRuns'
  _globals['_SCALE']._serialized_start=272
  _globals['_SCALE']._serialized_end=494
  _globals['_SCALELOG']._serialized_start=497
  _globals['_SCALELOG']._serialized_end=746
  _globals['_SIMULATIONRUN']._serialized_start=749
  _globals['_SIMULATIONRUN']._serialized_end=972
# @@protoc_insertion_point(module_scope)
