// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cavnue/messages/spatial/v1/utm.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto;
namespace cavnue {
namespace messages {
namespace spatial {
namespace v1 {
class UTMProjection;
struct UTMProjectionDefaultTypeInternal;
extern UTMProjectionDefaultTypeInternal _UTMProjection_default_instance_;
}  // namespace v1
}  // namespace spatial
}  // namespace messages
}  // namespace cavnue
PROTOBUF_NAMESPACE_OPEN
template <>
::cavnue::messages::spatial::v1::UTMProjection* Arena::CreateMaybeMessage<::cavnue::messages::spatial::v1::UTMProjection>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace cavnue {
namespace messages {
namespace spatial {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class UTMProjection final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cavnue.messages.spatial.v1.UTMProjection) */ {
 public:
  inline UTMProjection() : UTMProjection(nullptr) {}
  ~UTMProjection() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR UTMProjection(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UTMProjection(const UTMProjection& from);
  UTMProjection(UTMProjection&& from) noexcept
    : UTMProjection() {
    *this = ::std::move(from);
  }

  inline UTMProjection& operator=(const UTMProjection& from) {
    CopyFrom(from);
    return *this;
  }
  inline UTMProjection& operator=(UTMProjection&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UTMProjection& default_instance() {
    return *internal_default_instance();
  }
  static inline const UTMProjection* internal_default_instance() {
    return reinterpret_cast<const UTMProjection*>(
               &_UTMProjection_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UTMProjection& a, UTMProjection& b) {
    a.Swap(&b);
  }
  inline void Swap(UTMProjection* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UTMProjection* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UTMProjection* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UTMProjection>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UTMProjection& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UTMProjection& from) {
    UTMProjection::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UTMProjection* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "cavnue.messages.spatial.v1.UTMProjection";
  }
  protected:
  explicit UTMProjection(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kZoneFieldNumber = 1,
    kNorthFieldNumber = 2,
  };
  // int32 zone = 1 [json_name = "zone"];
  void clear_zone() ;
  ::int32_t zone() const;
  void set_zone(::int32_t value);

  private:
  ::int32_t _internal_zone() const;
  void _internal_set_zone(::int32_t value);

  public:
  // bool north = 2 [json_name = "north"];
  void clear_north() ;
  bool north() const;
  void set_north(bool value);

  private:
  bool _internal_north() const;
  void _internal_set_north(bool value);

  public:
  // @@protoc_insertion_point(class_scope:cavnue.messages.spatial.v1.UTMProjection)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::int32_t zone_;
    bool north_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UTMProjection

// int32 zone = 1 [json_name = "zone"];
inline void UTMProjection::clear_zone() {
  _impl_.zone_ = 0;
}
inline ::int32_t UTMProjection::zone() const {
  // @@protoc_insertion_point(field_get:cavnue.messages.spatial.v1.UTMProjection.zone)
  return _internal_zone();
}
inline void UTMProjection::set_zone(::int32_t value) {
  _internal_set_zone(value);
  // @@protoc_insertion_point(field_set:cavnue.messages.spatial.v1.UTMProjection.zone)
}
inline ::int32_t UTMProjection::_internal_zone() const {
  return _impl_.zone_;
}
inline void UTMProjection::_internal_set_zone(::int32_t value) {
  ;
  _impl_.zone_ = value;
}

// bool north = 2 [json_name = "north"];
inline void UTMProjection::clear_north() {
  _impl_.north_ = false;
}
inline bool UTMProjection::north() const {
  // @@protoc_insertion_point(field_get:cavnue.messages.spatial.v1.UTMProjection.north)
  return _internal_north();
}
inline void UTMProjection::set_north(bool value) {
  _internal_set_north(value);
  // @@protoc_insertion_point(field_set:cavnue.messages.spatial.v1.UTMProjection.north)
}
inline bool UTMProjection::_internal_north() const {
  return _impl_.north_;
}
inline void UTMProjection::_internal_set_north(bool value) {
  ;
  _impl_.north_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace spatial
}  // namespace messages
}  // namespace cavnue


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_cavnue_2fmessages_2fspatial_2fv1_2futm_2eproto_2epb_2eh
