# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/common/v1/field_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-cavnue/messages/common/v1/field_options.proto\x12\x19\x63\x61vnue.messages.common.v1\x1a google/protobuf/descriptor.proto*\xa0\x03\n\x05Units\x12\x15\n\x11UNITS_UNSPECIFIED\x10\x00\x12\x1b\n\x17UNITS_METERS_PER_SECOND\x10\x01\x12#\n\x1fUNITS_METERS_PER_SECOND_SQUARED\x10\x02\x12\x1d\n\x19UNITS_KILOMETERS_PER_HOUR\x10\x03\x12\x10\n\x0cUNITS_PIXELS\x10\x04\x12\x10\n\x0cUNITS_METERS\x10\x05\x12\x11\n\rUNITS_SECONDS\x10\x07\x12\x16\n\x12UNITS_MILLISECONDS\x10\x08\x12\x11\n\rUNITS_RADIANS\x10\t\x12\x11\n\rUNITS_DEGREES\x10\n\x12\x12\n\x0eUNITS_DECIBELS\x10\x0b\x12\x1e\n\x1aUNITS_MILLIMETERS_PER_HOUR\x10\x0c\x12\x11\n\rUNITS_CELSIUS\x10\r\x12\x1c\n\x18UNITS_DEGREES_PER_SECOND\x10\x0e\x12\'\n#UNITS_VEHICLES_PER_METER_PER_SECOND\x10\x0f\x12\x1c\n\x18UNITS_VEHICLES_PER_METER\x10\x10*]\n\x03\x43RS\x12\x13\n\x0f\x43RS_UNSPECIFIED\x10\x00\x12\r\n\tCRS_WGS84\x10\x01\x12\x0b\n\x07\x43RS_UTM\x10\x02\x12\x0b\n\x07\x43RS_ENU\x10\x03\x12\x0b\n\x07\x43RS_NED\x10\x04\x12\x0b\n\x07\x43RS_EGO\x10\x05:O\n\x05units\x12\x1d.google.protobuf.FieldOptions\x18\x91N \x01(\x0e\x32 .cavnue.messages.common.v1.Units:K\n\x03\x63rs\x12\x1d.google.protobuf.FieldOptions\x18\x92N \x01(\x0e\x32\x1e.cavnue.messages.common.v1.CRS:-\n\x04rows\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x9c\x01 \x01(\r:-\n\x04\x63ols\x12\x1d.google.protobuf.FieldOptions\x18\xa2\x9c\x01 \x01(\r:6\n\rautogenerated\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x08:3\n\nderivation\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x03(\t:4\n\x0bprimary_key\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.common.v1.field_options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(units)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(crs)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(rows)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(cols)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(autogenerated)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(derivation)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(primary_key)

  DESCRIPTOR._options = None
  _globals['_UNITS']._serialized_start=111
  _globals['_UNITS']._serialized_end=527
  _globals['_CRS']._serialized_start=529
  _globals['_CRS']._serialized_end=622
# @@protoc_insertion_point(module_scope)
