# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cavnue/messages/inference/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cavnue.messages.common.v1 import common_pb2 as cavnue_dot_messages_dot_common_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)cavnue/messages/inference/v1/events.proto\x12\x1c\x63\x61vnue.messages.inference.v1\x1a&cavnue/messages/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x04\n\x05\x45vent\x12\x31\n\x06header\x18\x01 \x01(\x0b\x32!.cavnue.messages.common.v1.Header\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x03\x12\x36\n\x04type\x18\x03 \x01(\x0e\x32(.cavnue.messages.inference.v1.Event.Type\x12>\n\x08severity\x18\x04 \x01(\x0e\x32,.cavnue.messages.inference.v1.Event.Severity\x12.\n\nstart_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12\x11\n\tactor_ids\x18\x08 \x03(\x03\"k\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rTYPE_IMPEDING\x10\x01\x12\x11\n\rTYPE_SPEEDING\x10\x02\x12\x13\n\x0fTYPE_STATIONARY\x10\x03\x12\x12\n\x0eTYPE_COLLISION\x10\x04\"S\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x13\n\x0fSEVERITY_HAZARD\x10\x01\x12\x18\n\x14SEVERITY_OF_INTEREST\x10\x02\"\xd7\x03\n\x0cTrafficEvent\x12\x31\n\x06header\x18\x01 \x01(\x0b\x32!.cavnue.messages.common.v1.Header\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x03\x12=\n\x04type\x18\x03 \x01(\x0e\x32/.cavnue.messages.inference.v1.TrafficEvent.Type\x12\x45\n\x08severity\x18\x04 \x01(\x0e\x32\x33.cavnue.messages.inference.v1.TrafficEvent.Severity\x12.\n\nstart_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12\x17\n\x0flane_segment_id\x18\x08 \x03(\x03\"1\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fTYPE_CONGESTION\x10\x01\">\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x18\n\x14SEVERITY_OF_INTEREST\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cavnue.messages.inference.v1.events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EVENT']._serialized_start=149
  _globals['_EVENT']._serialized_end=672
  _globals['_EVENT_TYPE']._serialized_start=480
  _globals['_EVENT_TYPE']._serialized_end=587
  _globals['_EVENT_SEVERITY']._serialized_start=589
  _globals['_EVENT_SEVERITY']._serialized_end=672
  _globals['_TRAFFICEVENT']._serialized_start=675
  _globals['_TRAFFICEVENT']._serialized_end=1146
  _globals['_TRAFFICEVENT_TYPE']._serialized_start=1033
  _globals['_TRAFFICEVENT_TYPE']._serialized_end=1082
  _globals['_TRAFFICEVENT_SEVERITY']._serialized_start=1084
  _globals['_TRAFFICEVENT_SEVERITY']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
